version: '3.1'
services:
  app:
    build: .
    container_name: refactor_code
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
  
  nginx:
    build:
      context: .
      dockerfile: docker/web.Dockerfile
    container_name: refactor_code_webserver
    ports:
      - 8082:80
    volumes:
      - ./:/var/www/html
    networks:
      - app-network
    depends_on:
      - app
    

networks:
  app-network:
    external: true
